### ISSUE TITLE
unable to generate a pdf since 0.16.1

### ISSUE THREAD

**Issue by russulae** [crowdagger/crowbook#122]
Hi !
I installed crowbook 0.16.1 with cargo on an up-to-date Debian unstable. When I'm trying to generate a pdf from a pretty basic text file crowbook fails with the following error (can't find a more precise error message):

```
20:41:00 [DEBUG] (1) crowbook::book: Analyse du chapitre: test.md...
20:41:00 [DEBUG] (1) crowbook::book: Ignoring YAML block:
                            
 
20:41:00 [DEBUG] (1) crowbook::book: Tentative de générer le format pdf...
20:41:00 [DEBUG] (1) crowbook::latex: En train d'essayer de lancer LaTeX sur le fichier généré
20:41:02 [DEBUG] (1) crowbook::zipper: xelatex ne ne s'est pas terminé avec succès : 
20:41:02 [ERROR] crowbook::book: Erreur dans le rendu de pdf : Erreur durant l'édition de fichiers temporaires :xelatex ne s'est pas terminé avec succès
```

my test.book file :

```
author: russulae
title: test crowbook
date: "2024"
version: "ver. 1"
#license: "Creative Commons BY-NC-SA"

## Formats de sortie

#input.clean.ligature.dashes
#input.clean.ligature.guillemets: true

# Décommenter et remplir pour générer des fichiers
# output.html: test.html
# output.epub: test.epub
 output.pdf: test.pdf

# Ou décommenter ce qui suit pour générer des fichiers PDF, HTML et EPUB selon le nom de ce fichier
# output: [pdf, epub, html]

# Décommenter et remplir pour configurer une image de couverture (pour l'Epub)
#cover: couv.png


## Liste des chapitres
- test.md
```
and  test.md only contains the word "test"

I'm able to generate a pdf with crowbook 0.15.1 (I can't remember how I installed it at the time)

**Comment by crowdagger** [comment]
Sorry about the delay. If that is still relevant (or for any similar error), the error comes from xelatex. For more information, generate a .tex file, then run xelatex on it : 

```
$ crowbook --to tex --output foo.tex foo.book
$ xelatex foo.tex
```

**Comment by russulae** [comment]
> Sorry about the delay.

 no problem, 15.1 works fine in the mean time…

> If that is still relevant (or for any similar error), the error comes from xelatex. For more information, generate a .tex file, then run xelatex on it

I still have the issue, here is the xelatex error (I have no idea what to do with it) :

```
! LaTeX Error: File `puenc-greek.def' not found.
```

I don't understand why it's looking for greek punks, maybe there is broken symlink in `/athens/exarchia/` (sorry, that was a joke)

**Comment by crowdagger** [comment]
Oh yeah I think I had the same at some point. I think it's more related to this : https://github.com/latex3/hyperref/issues/343 
AFAIK, hyperref (used for the links) depends on the greek-fontenc package. Apt installing  texlive-lang-greek should fix it. Maybe.

**Comment by russulae** [comment]
thanks thats

**Comment by russulae** [comment]
thanks, that was the issue !
